In [2]:
import numpy as np


In [2]:
lista = [1,2,3]
lista

[1, 2, 3]

In [3]:
arr = np.array(lista)
arr
type(arr)

numpy.ndarray

In [4]:
matriz = [[1,2,3],[4,5,6],[6,7,8]]
matriz
#matriz[0][0]

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [5]:
nparr = np.array(matriz)
nparr
type(nparr)

numpy.ndarray

#******metodos da numpy*********

##arange()

In [6]:
# primeiro elemento, inclusivo; segundo elemento, exclusivo
np.arange(0,10)
#np.arange(0,10,2) com step

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

ZEROS()

In [7]:
np.zeros(3) # padrão é comum criar como ponto flutuante (0.)

# ao inves de array de zeros com p.flutuante (float)
z = np.zeros(5,dtype=int)
z

array([0, 0, 0, 0, 0])

matriz com mais de uma dimensão

In [8]:
np.zeros((3,3,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

ones()

In [9]:
np.ones(4)

np.ones(4,dtype=int)

array([1, 1, 1, 1])

##linspace()

In [10]:
np.linspace(0,50,5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [41]:
#array bidimensional
#com 11 elementos, no eixo 1 = axis = 1
np.linspace([0,10],[2,40],11,axis=1)

#entre o 0 e 2, 11 elementos
#entre o 10 e 40, 11 elementos
# array([[ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ],
#        [10. , 13. , 16. , 19. , 22. , 25. , 28. , 31. , 34. , 37. , 40. ]])


array([[ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ],
       [10. , 13. , 16. , 19. , 22. , 25. , 28. , 31. , 34. , 37. , 40. ]])

In [11]:
np.linspace(0,100,dtype=int) # divida por 50 é o padrão quando não informado ( acho que é o step)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

matriz identidade = 0 e 1

EYE()

In [12]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## sub modulo ramdom

## rand()
## usa distribuição uniforme: mesma chance de um número sair tanto quanto outro


In [13]:
np.random.rand(5) # faz referencia ao submodulo rand

array([0.76381398, 0.22069786, 0.63887752, 0.1024344 , 0.27351949])

In [14]:
np.random.rand(3,3) # faz referencia ao submodulo rand

array([[0.88449437, 0.65283393, 0.66861827],
       [0.86172294, 0.28714013, 0.32727873],
       [0.13677683, 0.58566983, 0.61228253]])

In [15]:
np.random.rand(5,5,2) # faz referencia ao submodulo rand

array([[[0.13519806, 0.58368548],
        [0.68156574, 0.16777407],
        [0.03514163, 0.47563769],
        [0.29722925, 0.96144208],
        [0.83971286, 0.39010666]],

       [[0.10733962, 0.56304338],
        [0.36728271, 0.59641572],
        [0.14300359, 0.73170389],
        [0.10251672, 0.71099252],
        [0.04652866, 0.162888  ]],

       [[0.64046327, 0.67020528],
        [0.98154854, 0.03821103],
        [0.89659082, 0.43932088],
        [0.33462755, 0.0936286 ],
        [0.13309618, 0.07599634]],

       [[0.92824304, 0.37685151],
        [0.64792649, 0.77888528],
        [0.27706298, 0.94252887],
        [0.3302901 , 0.03228698],
        [0.57434151, 0.06104323]],

       [[0.9796342 , 0.3142131 ],
        [0.5581884 , 0.86624628],
        [0.43097925, 0.1747002 ],
        [0.02327906, 0.35399335],
        [0.11777558, 0.65713616]]])

In [16]:
#operação escalar = aplica multiplicação por 10 em todos os elementos
np.random.rand(3,3,2) * 10

array([[[6.85494131, 0.82579687],
        [5.36256616, 0.52274442],
        [4.80827972, 8.00575132]],

       [[2.88294322, 5.34417855],
        [3.31353067, 3.5675241 ],
        [7.79821907, 9.70646813]],

       [[0.40092911, 3.3607894 ],
        [9.06206744, 8.71222667],
        [7.91723934, 6.34622294]]])

## randn()
## usa distribuição normal - é a curva

In [17]:
np.random.randn(5)

array([ 1.16643072, -0.21752081, -0.61095738, -2.9778088 , -1.44057957])

## randint()

In [18]:
#np.random.randint(1,10) # retorna tipo int
np.random.randint(1,10, size=(2,4)) #retorna matriz


array([[4, 9, 1, 9],
       [5, 4, 6, 6]])

## transformar matrizes em formar diferentes, mudar a forma

## reshape()

In [19]:
a = np.random.rand(20)
a

a.shape # tupla de unico elemento

# a.shape # tupla de unico elemento
# #pra tirar a virgula ai retorna type = int
# a.shape[0]



(20,)


## fazer reshape

In [21]:
a = a.reshape(2,10)

In [22]:
a.shape

(2, 10)

In [25]:
#a.reshape(2,5)# assim da erro pq a quantidade de elementos mudaria, aqui o a.shape seria 10
a = a.reshape(4,5) # funciona pq o resultado de a.shape = 20

## descobrir valores de alguns valores, elemento max, min etc.

In [26]:
a.max(axis=1) # busca o elemento maximo de cara uma das linhas, eixo x acho

array([0.90735851, 0.89677932, 0.51837496, 0.91516934])

In [27]:
a

array([[4.84239143e-01, 7.96321405e-02, 4.27161750e-01, 2.98524603e-01,
        9.07358513e-01],
       [5.37757160e-01, 6.25681945e-01, 8.96779320e-01, 8.24902667e-01,
        1.90575082e-01],
       [3.09296137e-01, 1.98269830e-01, 4.74825519e-01, 3.34529201e-01,
        5.18374960e-01],
       [8.25565582e-05, 7.69376250e-01, 9.15169341e-01, 6.89916237e-02,
        7.91111307e-01]])

In [28]:
#retorna a posição do valor maximo
a.argmax(axis = 1) #ou a[a.argmax(])

array([4, 2, 4, 2], dtype=int64)

In [29]:
a.min()

8.255655820110785e-05

In [30]:
a.argmin()

15

## metodos que dao estatisticas sobre o espaço amostral

In [31]:
a

array([[4.84239143e-01, 7.96321405e-02, 4.27161750e-01, 2.98524603e-01,
        9.07358513e-01],
       [5.37757160e-01, 6.25681945e-01, 8.96779320e-01, 8.24902667e-01,
        1.90575082e-01],
       [3.09296137e-01, 1.98269830e-01, 4.74825519e-01, 3.34529201e-01,
        5.18374960e-01],
       [8.25565582e-05, 7.69376250e-01, 9.15169341e-01, 6.89916237e-02,
        7.91111307e-01]])

In [92]:
#media
a.mean()

0.5617962729777821

In [94]:
a.mean(axis=1)

array([0.52637309, 0.64721546, 0.6770121 , 0.39658445])

In [96]:
#desvip adrão

a.std()
#a.std(axis = 1)


0.25558159890360177

In [98]:
a.sum() # a.sum(axis = 1)

11.235925459555641

## manipular elementos da matriz ja criada


In [32]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [108]:
#metodo da numpy e nao do array
np.insert(a, 3, 50) # nao altera a variavel original


array([ 1,  2,  3, 50,  4,  5,  6,  7])

In [1]:
np.insert(a,(3,6),90) # insere em mais de uma posição ao mesmo tempo

NameError: name 'np' is not defined

In [3]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
np.insert(b,[1],[[6],[9]], axis = 0)

array([[ 0,  1,  2,  3],
       [ 6,  6,  6,  6],
       [ 9,  9,  9,  9],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
np.insert(b,[1],[[6],[7],[9]], axis = 1)

array([[ 0,  6,  1,  2,  3],
       [ 4,  7,  5,  6,  7],
       [ 8,  9,  9, 10, 11]])

In [136]:
np.insert(b,(0,3),55, axis = 0)

array([[55, 55, 55, 55],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [55, 55, 55, 55]])

In [137]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
np.delete(b,1,0)

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [146]:
#np.delete(b,[1:3],0) # operação de slice não funcioan em algumas operações

# tem que usar o s_ que é o slice no numpy
np.delete(b,np.s_[1:3],1)

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11]])

In [150]:
c = np.arange(0,100)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [151]:
np.delete(c,np.s_[::2])

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [152]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [153]:
c[50] = 999
c

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49, 999,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99])

In [154]:
d = np.arange(12).reshape(3,4)
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [155]:
d[2][2] = 999
d

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9, 999,  11]])

## broadcasting e escalares ( não precisa usar map pra fazer operações igual listas)

In [156]:
r = np.arange(0,11)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [157]:
r * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [159]:
rs = np.arange(1,10).reshape(3,3)
rs

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [164]:
#retorna novo array, não mudando o 
rs * 2

array([[   2,    4,    6],
       [ 800, 1000, 1200],
       [  14,   16,   18]])

In [165]:
#aqui alterou o array
rs[1] = rs[1] * 100
rs

array([[    1,     2,     3],
       [40000, 50000, 60000],
       [    7,     8,     9]])

In [168]:
x = np.arange(1,21).reshape(4,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [169]:
z = np.arange(1,6)
z

array([1, 2, 3, 4, 5])

In [170]:
x*z

array([[  1,   4,   9,  16,  25],
       [  6,  14,  24,  36,  50],
       [ 11,  24,  39,  56,  75],
       [ 16,  34,  54,  76, 100]])

In [176]:
#pra pegar todas as linhas, e multiplica a coluna 1
b[:,1] = b[:,1] * 2
b

array([[  0,  64,   2,   3],
       [  4, 320,   6,   7],
       [  8, 576,  10,  11]])

In [192]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [178]:
a[0],a[1],a[2]

(0, 1, 2)

In [180]:
a[-1] # reverte a ordem da matriz

9

In [183]:
a[::-1]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [185]:
a = np.diag(np.arange(5))
a

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [186]:
a[1,1]

1

In [187]:
a[1,1] = 99
a

array([[ 0,  0,  0,  0,  0],
       [ 0, 99,  0,  0,  0],
       [ 0,  0,  2,  0,  0],
       [ 0,  0,  0,  3,  0],
       [ 0,  0,  0,  0,  4]])

In [188]:
a[4:,4:,]

array([[4]])

In [193]:
even = (a % 2) == 0
even

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [194]:
a[even]

array([0, 2, 4, 6, 8])

In [203]:
a[np.where(np.logical_and(a > 1, a < 10))]

array([2, 3, 4, 5, 6, 7, 8, 9])